{
 "title": "Go DB loadtest",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Average duration of operations over the last 5 minutes",
   "type": "timeseries",
   "description": "This method computes the average duration of operations by looking at the rates of change in the total duration and count. It provides a more accurate average over time, smoothing out short-term fluctuations and considering the latest data trends.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(db_ops_duration_seconds_total_sum[5m])) by (db_type, query_type) /\nsum(rate(db_ops_duration_seconds_total_count[5m])) by (db_type, query_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total operations processed",
   "type": "timeseries",
   "description": "Average rate of ops per second over the past 1 minute.",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "query" } },
   "targets": [
    {
     "expr": "sum(rate(db_ops_processed_total[1m])) by (db_type, query_type)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Average duration in seconds for total operations",
   "type": "timeseries",
   "description": "This approach calculates the average duration by directly dividing the total sum of durations by the total count of operations. It works well for a point in time but may not account for the rate of change or smooth out fluctuations over time.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(db_ops_duration_seconds_total_sum/db_ops_duration_seconds_total_count) by (db_type, query_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average duration in seconds per operation",
   "type": "timeseries",
   "description": "Average duration in seconds per operation",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(db_ops_duration_seconds_sum/db_ops_duration_seconds_count) by (db_type, query_type)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}